#!/usr/bin/env bash
# Regenerate the Homebrew tap formula for a release tag and push it to the tap repo, so a `git tag`
# is the ONLY manual step of a release. Run by the cold-frame Release workflow's `bump-tap` job.
#
# Needs $HOMEBREW_TAP_TOKEN — a token with `contents:write` on coldzero94/homebrew-coldframe (a
# fine-grained PAT scoped to that one repo, stored as the `HOMEBREW_TAP_TOKEN` repo secret). If it is
# absent the script SKIPS (exit 0) so a release never fails just because auto-bump isn't configured.
#
# Usage: HOMEBREW_TAP_TOKEN=… packaging/homebrew/bump-tap.sh v0.1.2
set -euo pipefail

TAG="${1:?usage: bump-tap.sh <tag e.g. v0.1.0>}"
REPO="${GITHUB_REPOSITORY:-coldzero94/cold-frame}"
TAP="coldzero94/homebrew-coldframe"
VERSION="${TAG#v}"
BASE="https://github.com/${REPO}/releases/download/${TAG}"

if [ -z "${HOMEBREW_TAP_TOKEN:-}" ]; then
  echo "::warning::HOMEBREW_TAP_TOKEN not set — skipping Homebrew tap auto-update." >&2
  exit 0
fi

_sha() { if command -v sha256sum >/dev/null 2>&1; then sha256sum; else shasum -a 256; fi | awk '{print $1}'; }
sha() { curl -fsSL "$1" | _sha; }

ARM="$(sha "${BASE}/cold-frame-macos-arm64")"
LNX="$(sha "${BASE}/cold-frame-linux-x86_64")"

work="$(mktemp -d)"
git clone --depth 1 "https://x-access-token:${HOMEBREW_TAP_TOKEN}@github.com/${TAP}.git" "$work"
mkdir -p "$work/Formula"

cat > "$work/Formula/cold-frame.rb" <<RUBY
# Auto-generated by the cold-frame Release workflow (packaging/homebrew/bump-tap.sh) — do not edit.
# Installs the self-contained binary (CLI + MCP in one file; no Python, offline). macOS = Apple
# Silicon only (Intel is out of scope). \`brew install coldzero94/coldframe/cold-frame\`.
class ColdFrame < Formula
  desc "Local-first ownable memory layer for LLM agents (one offline SQLite file)"
  homepage "https://github.com/${REPO}"
  version "${VERSION}"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "${BASE}/cold-frame-macos-arm64"
      sha256 "${ARM}"
    end
  end
  on_linux do
    url "${BASE}/cold-frame-linux-x86_64"
    sha256 "${LNX}"
  end

  def install
    bin.install Dir["cold-frame-*"].first => "cold-frame"
    chmod 0755, bin/"cold-frame"
  end

  test do
    assert_match version, shell_output("#{bin}/cold-frame --version")
  end

  def caveats
    <<~EOS
      Turn on AUTOMATIC memory in Claude Code (recall every session, capture as you work):
        cold-frame hook install
        claude mcp add cold-frame -- cold-frame mcp

      Your memory lives in ~/.cold-frame/memory.db — one file, yours, offline. Browse it:
        cold-frame ui
    EOS
  end
end
RUBY

cd "$work"
git config user.name "github-actions[bot]"
git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
git add Formula/cold-frame.rb
git commit -m "cold-frame ${VERSION}" || { echo "tap already up to date for ${VERSION}"; exit 0; }
git push
echo "Homebrew tap updated → cold-frame ${VERSION}"
