# Homebrew formula for Coldframe (a local-first, ownable memory layer for LLM agents).
#
# This is the TAP formula: `brew install coldzero94/coldframe/cold-frame`. It builds an isolated
# Python virtualenv under the Cellar and installs cold-frame + the [mcp] extra (so the MCP
# server — `cold-frame mcp` — works out of the box for Claude Code), resolving the dependency
# tree from PyPI at build time. That network-at-build style is fine for a third-party tap; the
# homebrew-core variant (vendored, sha256-pinned `resource` blocks generated by
# `brew update-python-resources`) is documented in RELEASE.md for later submission.
#
# RELEASE: the two values below are filled when the release tag is cut (both depend on the
# final project name + repo, which are gated on D19 — name/PyPI/trademark clearance):
#   url    → the GitHub release source tarball for the tag
#   sha256 → shasum -a 256 of that tarball
class ColdFrame < Formula
  include Language::Python::Virtualenv

  desc "Local-first ownable memory layer for LLM agents (one offline SQLite file)"
  homepage "https://github.com/coldzero94/cold-frame" # RELEASE: real repo URL (D19)
  url "https://github.com/coldzero94/cold-frame/archive/refs/tags/v0.1.0.tar.gz" # RELEASE
  sha256 "0000000000000000000000000000000000000000000000000000000000000000" # RELEASE: tarball sha256
  license "Apache-2.0"

  depends_on "python@3.12"
  # numpy + pydantic-core + the mcp tree (cryptography/cffi/rpds-py) build native wheels; pip
  # handles that inside the venv. No system libs beyond a compiler toolchain (already present).

  def install
    venv = virtualenv_create(libexec, Formula["python@3.12"].opt_bin/"python3.12")
    # install the unpacked formula source WITH the mcp extra → core + a working MCP server.
    # deps resolve from PyPI (tap-style); pin set captured in RELEASE.md for the vendored variant.
    venv.pip_install "#{buildpath}[mcp]"
    bin.install_symlink libexec/"bin/cold-frame"
  end

  def caveats
    <<~EOS
      Turn on AUTOMATIC memory in Claude Code (recall every session, capture as you work):
        cold-frame hook install
        claude mcp add cold-frame -- cold-frame mcp

      Your memory lives in ~/.cold-frame/memory.db — one file, yours, offline. Browse it:
        cold-frame ui
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/cold-frame --version")
    ENV["COLD_FRAME_DB"] = testpath/"memory.db"
    system bin/"cold-frame", "add", "I prefer dark roast coffee"
    assert_match "coffee", shell_output("#{bin}/cold-frame search coffee")
    # the MCP extra is bundled, so the server module must import (no missing-dep hint)
    system bin/"cold-frame", "doctor"
  end
end
